## Sampling and Simulation:

In [2]:
import numpy as np

In [22]:
# Getting Random Samples (pseudo-random)
np.random.seed(1)
n = 10
how_many = 5
random_sample1 = np.random.choice(np.arange(1, n+1), how_many, replace=False) # replace=False for no duplicates/replacement
random_sample2 = np.random.choice(np.arange(1, n+1), how_many, replace=True) # replace=True for yes duplicates/replacement
print(random_sample1)
print(random_sample2)

[ 3 10  7  5  1]
[ 8  7 10  3  5]


In [23]:
# Generating Random Permutation
np.random.seed(2) # randomizer

m = 1
n = 10

vector = np.arange(m, n+1)
print(vector)

np.random.shuffle(vector) # Permutate
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]
[ 3 10  7  5  1  4  2  8  9  6]


In [27]:
# Generating Random Letters Permutation
np.random.seed(3) # randomizer

import string
alphabets = list(string.ascii_lowercase)
print(alphabets)

# randomly choose 7 letters, concatenate into a string
seven_random_letters = ''.join(np.random.choice(alphabets, 7, replace=False))
print(seven_random_letters)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
srmxpqn


In [32]:
# Specifying the probability of getting a certain number
np.random.seed(5)
np.random.choice(4, 3, replace=True, p=[0.1,0.2,0.3,0.4]) # (range[0,1,2,3]), how_many, replacement/duplicates, probabilities of each nums)

array([1, 3, 1], dtype=int32)