In [2]:
import numpy as np

## Vectors:

In [3]:
vector = np.array([3,1,4,1,5,9])
print(vector)

[3 1 4 1 5 9]


In [4]:
# Sum, Min, Max
print(vector.sum())
print(vector.min())
print(vector.max())

# Length
print(vector.size)
print(len(vector))

23
1
9
6
6


In [5]:
# Generating a sequence (1,2,...,n)
m = 1
n = 10

vector = np.arange(m ,n+1)
print(vector)

c = np.arange(n, m-1, -1)
print(vector_reversed)

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


# Accessing ith element
print(vector[0])
print(vector[1])
print('index 1 in reversed vector:', vector_reversed[1])
print('index 9 in reversed vector:',vector_reversed[9])

In [13]:
# Acessing Subset/Subvector

target_subset = ([1, 3, 5])
print('Subset of normal vector:', vector[target_subset])
print('Subset of reversed vector:', vector_reversed[target_subset])

# Filtering Using Boolean Indexer
boolean_indexer = np.array([True, True, False, True, False, True, False, True, True, True])
print(vector[boolean_indexer])
print(vector_reversed[boolean_indexer])

Subset of normal vector: [2 4 6]
Subset of reversed vector: [9 7 5]
[ 1  2  4  6  8  9 10]
[10  9  7  5  3  2  1]


In [17]:
# Cube
print('Cubed vector:', vector**3)
print('Cubed reversed vector:',vector_reversed**3)

Cubed vector: [   1    8   27   64  125  216  343  512  729 1000]
Cubed reversed vector: [1000  729  512  343  216  125   64   27    8    1]


In [18]:
# Getting the vector (1, 1/(2^2), 1/(3^2),...,1/(100^2))
1 / np.arange(1, 101)**2

array([1.00000000e+00, 2.50000000e-01, 1.11111111e-01, 6.25000000e-02,
       4.00000000e-02, 2.77777778e-02, 2.04081633e-02, 1.56250000e-02,
       1.23456790e-02, 1.00000000e-02, 8.26446281e-03, 6.94444444e-03,
       5.91715976e-03, 5.10204082e-03, 4.44444444e-03, 3.90625000e-03,
       3.46020761e-03, 3.08641975e-03, 2.77008310e-03, 2.50000000e-03,
       2.26757370e-03, 2.06611570e-03, 1.89035917e-03, 1.73611111e-03,
       1.60000000e-03, 1.47928994e-03, 1.37174211e-03, 1.27551020e-03,
       1.18906064e-03, 1.11111111e-03, 1.04058273e-03, 9.76562500e-04,
       9.18273646e-04, 8.65051903e-04, 8.16326531e-04, 7.71604938e-04,
       7.30460190e-04, 6.92520776e-04, 6.57462196e-04, 6.25000000e-04,
       5.94883998e-04, 5.66893424e-04, 5.40832883e-04, 5.16528926e-04,
       4.93827160e-04, 4.72589792e-04, 4.52693526e-04, 4.34027778e-04,
       4.16493128e-04, 4.00000000e-04, 3.84467512e-04, 3.69822485e-04,
       3.55998576e-04, 3.42935528e-04, 3.30578512e-04, 3.18877551e-04,
      

In [20]:
# Adding Using Numpy.array
print(vector+3)
print(vector_reversed+3)

[ 4  5  6  7  8  9 10 11 12 13]
[13 12 11 10  9  8  7  6  5  4]
